// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: paxos/v1/paxos.proto

package paxosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposalNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int64                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalNumber) Reset() {
	*x = ProposalNumber{}
	mi := &file_paxos_v1_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalNumber) ProtoMessage() {}

func (x *ProposalNumber) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_v1_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalNumber.ProtoReflect.Descriptor instead.
func (*ProposalNumber) Descriptor() ([]byte, []int) {
	return file_paxos_v1_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalNumber) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProposalNumber) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *ProposalNumber        `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	ProposerId    int64                  `protobuf:"varint,2,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_paxos_v1_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_v1_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_paxos_v1_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareRequest) GetProposal() *ProposalNumber {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *PrepareRequest) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

type PrepareResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Promised         bool                   `protobuf:"varint,1,opt,name=promised,proto3" json:"promised,omitempty"`
	HighestPromised  *ProposalNumber        `protobuf:"bytes,2,opt,name=highest_promised,json=highestPromised,proto3" json:"highest_promised,omitempty"`
	AcceptedProposal *ProposalNumber        `protobuf:"bytes,3,opt,name=accepted_proposal,json=acceptedProposal,proto3" json:"accepted_proposal,omitempty"`
	AcceptedValue    uint64                 `protobuf:"varint,4,opt,name=accepted_value,json=acceptedValue,proto3" json:"accepted_value,omitempty"`
	HasAccepted      bool                   `protobuf:"varint,5,opt,name=has_accepted,json=hasAccepted,proto3" json:"has_accepted,omitempty"`
	AcceptorId       int64                  `protobuf:"varint,6,opt,name=acceptor_id,json=acceptorId,proto3" json:"acceptor_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_paxos_v1_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_v1_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_paxos_v1_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareResponse) GetPromised() bool {
	if x != nil {
		return x.Promised
	}
	return false
}

func (x *PrepareResponse) GetHighestPromised() *ProposalNumber {
	if x != nil {
		return x.HighestPromised
	}
	return nil
}

func (x *PrepareResponse) GetAcceptedProposal() *ProposalNumber {
	if x != nil {
		return x.AcceptedProposal
	}
	return nil
}

func (x *PrepareResponse) GetAcceptedValue() uint64 {
	if x != nil {
		return x.AcceptedValue
	}
	return 0
}

func (x *PrepareResponse) GetHasAccepted() bool {
	if x != nil {
		return x.HasAccepted
	}
	return false
}

func (x *PrepareResponse) GetAcceptorId() int64 {
	if x != nil {
		return x.AcceptorId
	}
	return 0
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *ProposalNumber        `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	ProposerId    int64                  `protobuf:"varint,3,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_paxos_v1_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_v1_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_paxos_v1_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptRequest) GetProposal() *ProposalNumber {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *AcceptRequest) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AcceptRequest) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

type AcceptResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	HighestPromised *ProposalNumber        `protobuf:"bytes,2,opt,name=highest_promised,json=highestPromised,proto3" json:"highest_promised,omitempty"`
	AcceptorId      int64                  `protobuf:"varint,3,opt,name=acceptor_id,json=acceptorId,proto3" json:"acceptor_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_paxos_v1_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_v1_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_paxos_v1_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AcceptResponse) GetHighestPromised() *ProposalNumber {
	if x != nil {
		return x.HighestPromised
	}
	return nil
}

func (x *AcceptResponse) GetAcceptorId() int64 {
	if x != nil {
		return x.AcceptorId
	}
	return 0
}

var File_paxos_v1_paxos_proto protoreflect.FileDescriptor

const file_paxos_v1_paxos_proto_rawDesc = "" +
	"\n" +
	"\x14paxos/v1/paxos.proto\x12\bpaxos.v1\"?\n" +
	"\x0eProposalNumber\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x03R\x05round\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x03R\x06nodeId\"g\n" +
	"\x0ePrepareRequest\x124\n" +
	"\bproposal\x18\x01 \x01(\v2\x18.paxos.v1.ProposalNumberR\bproposal\x12\x1f\n" +
	"\vproposer_id\x18\x02 \x01(\x03R\n" +
	"proposerId\"\xa4\x02\n" +
	"\x0fPrepareResponse\x12\x1a\n" +
	"\bpromised\x18\x01 \x01(\bR\bpromised\x12C\n" +
	"\x10highest_promised\x18\x02 \x01(\v2\x18.paxos.v1.ProposalNumberR\x0fhighestPromised\x12E\n" +
	"\x11accepted_proposal\x18\x03 \x01(\v2\x18.paxos.v1.ProposalNumberR\x10acceptedProposal\x12%\n" +
	"\x0eaccepted_value\x18\x04 \x01(\x04R\racceptedValue\x12!\n" +
	"\fhas_accepted\x18\x05 \x01(\bR\vhasAccepted\x12\x1f\n" +
	"\vacceptor_id\x18\x06 \x01(\x03R\n" +
	"acceptorId\"|\n" +
	"\rAcceptRequest\x124\n" +
	"\bproposal\x18\x01 \x01(\v2\x18.paxos.v1.ProposalNumberR\bproposal\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\x12\x1f\n" +
	"\vproposer_id\x18\x03 \x01(\x03R\n" +
	"proposerId\"\x92\x01\n" +
	"\x0eAcceptResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12C\n" +
	"\x10highest_promised\x18\x02 \x01(\v2\x18.paxos.v1.ProposalNumberR\x0fhighestPromised\x12\x1f\n" +
	"\vacceptor_id\x18\x03 \x01(\x03R\n" +
	"acceptorId2\x84\x01\n" +
	"\x05Paxos\x12>\n" +
	"\aPrepare\x12\x18.paxos.v1.PrepareRequest\x1a\x19.paxos.v1.PrepareResponse\x12;\n" +
	"\x06Accept\x12\x17.paxos.v1.AcceptRequest\x1a\x18.paxos.v1.AcceptResponseBAZ?github.com/ethandedalus/single-decree-paxos/pkg/paxosv1;paxosv1b\x06proto3"

var (
	file_paxos_v1_paxos_proto_rawDescOnce sync.Once
	file_paxos_v1_paxos_proto_rawDescData []byte
)

func file_paxos_v1_paxos_proto_rawDescGZIP() []byte {
	file_paxos_v1_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_v1_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_v1_paxos_proto_rawDesc), len(file_paxos_v1_paxos_proto_rawDesc)))
	})
	return file_paxos_v1_paxos_proto_rawDescData
}

var file_paxos_v1_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_paxos_v1_paxos_proto_goTypes = []any{
	(*ProposalNumber)(nil),  // 0: paxos.v1.ProposalNumber
	(*PrepareRequest)(nil),  // 1: paxos.v1.PrepareRequest
	(*PrepareResponse)(nil), // 2: paxos.v1.PrepareResponse
	(*AcceptRequest)(nil),   // 3: paxos.v1.AcceptRequest
	(*AcceptResponse)(nil),  // 4: paxos.v1.AcceptResponse
}
var file_paxos_v1_paxos_proto_depIdxs = []int32{
	0, // 0: paxos.v1.PrepareRequest.proposal:type_name -> paxos.v1.ProposalNumber
	0, // 1: paxos.v1.PrepareResponse.highest_promised:type_name -> paxos.v1.ProposalNumber
	0, // 2: paxos.v1.PrepareResponse.accepted_proposal:type_name -> paxos.v1.ProposalNumber
	0, // 3: paxos.v1.AcceptRequest.proposal:type_name -> paxos.v1.ProposalNumber
	0, // 4: paxos.v1.AcceptResponse.highest_promised:type_name -> paxos.v1.ProposalNumber
	1, // 5: paxos.v1.Paxos.Prepare:input_type -> paxos.v1.PrepareRequest
	3, // 6: paxos.v1.Paxos.Accept:input_type -> paxos.v1.AcceptRequest
	2, // 7: paxos.v1.Paxos.Prepare:output_type -> paxos.v1.PrepareResponse
	4, // 8: paxos.v1.Paxos.Accept:output_type -> paxos.v1.AcceptResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_paxos_v1_paxos_proto_init() }
func file_paxos_v1_paxos_proto_init() {
	if File_paxos_v1_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_v1_paxos_proto_rawDesc), len(file_paxos_v1_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_v1_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_v1_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_v1_paxos_proto_msgTypes,
	}.Build()
	File_paxos_v1_paxos_proto = out.File
	file_paxos_v1_paxos_proto_goTypes = nil
	file_paxos_v1_paxos_proto_depIdxs = nil
}
